server/main/urls.py
from django.urls import path
from main.views import (
    main, contacts
)


app_name = 'main'

urlpatterns = [
    path('', main, name='main'),
    path('contacts/', contacts, name='contacts'),
]

server/server/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from rest_framework.routers import DefaultRouter
from products.viewsets import ProductViewSet, CategoryViewSet


router = DefaultRouter()
router.register('products', ProductViewSet)
router.register('categories', CategoryViewSet)

urlpatterns = [
    path('api/', include(router.urls)),
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('categories/', include('products.urls.categories')),
    path('accounts/', include('accounts.urls')),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/server/templates/server/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="ru">
    {% block head %}
        <head>
            <meta charset="UTF-8">
            <title>
                {% block title %}
                    {{ title|title }}
                {% endblock %}
            </title>

            {% block css %}
                <link rel="stylesheet"
                  href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
                  integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU"
                  crossorigin="anonymous">
                <link rel="stylesheet" href="{% static 'server/css/base.css' %}">
                <link rel="stylesheet" href="{% static 'server/css/menu.css' %}">

                {% for link in link_list %}
                    {% if link != '' %}
                        <link rel="stylesheet" href="{% static link %}">
                    {% endif %}
                {% endfor %}
            {% endblock %}

            {% block js %}

            {% endblock %}
        </head>
    {% endblock %}

    {% block body %}
        <body class="body_main">
            {% block header_main %}
                <div class="header_main">
                    <div class="main_wrap">
                        <a href="{% url 'main:main' %}" class="logo"></a>
                        <div class="shop_name_wrap">
                            <div class="shop_name_main">
                                Сундук с сокровищами
                            </div>
                            <div class="shop_name_text">
                                Добро пожаловать в магазин настольных игр
                            </div>
                        </div>
                        <div class="social_icons">
                            <a href="#">
                                <i class="fab fa-facebook-f"></i>
                            </a>
                            <a href="#">
                                <i class="fab fa-twitter"></i>
                            </a>
                            <a href="#">
                                <i class="fab fa-youtube"></i>
                            </a>
                            <a href="#">
                                <i class="fab fa-pinterest-p"></i>
                            </a>
                            <a href="#">
                                <i class="fab fa-instagram"></i>
                            </a>
                        </div>
                    </div>
                </div>
            {% endblock %}

            <div class="content_main">
                <div class="main_wrap">
                    {% block content_left %}
                        <div class="content_left">
                            {% include 'server/includes/inc_main_menu.html' %}
                            <div class="now_is_open">
                                <span>Now <br> is <br> open!</span>
                            </div>
                        </div>
                    {% endblock %}
                    <div class="content_right">
                        {% block content_right %}
                        {% endblock %}
                    </div>

                    {% block brends_main %}
                    {% endblock %}

                    {% block instagram %}
                    {% endblock %}

                    {% block social_buttons %}
                    {% endblock %}
                </div>
            </div>

            {% block footer_content %}
                <div class="footer_content">
                    <div class="main_wrap">
                        <div class="footer_content_wrap">
                            <div>
                                <div class="column_head">
                                    Меню
                                </div>
                                <div class="column_link">
                                    <a href="{% url 'main:main' %}">Главная</a>
                                    <a href="{% url 'products:main' %}">Каталог</a>
                                    <a href="{% url 'main:contacts' %}">Контакты</a>
                                </div>
                            </div>
                            <div>
                                <div class="column_head">
                                    Our Account
                                </div>
                                <div class="column_link">
                                    <a href="#">Your Account</a>
                                    <a href="#">Personal information</a>
                                    <a href="#">Addresses</a>
                                    <a href="#">Discount</a>
                                    <a href="#">Orders history</a>
                                    <a href="#">Addresses</a>
                                    <a href="#">Search Terms</a>
                                </div>
                            </div>
                            <div>
                                <div class="column_head">
                                    Our Support
                                </div>
                                <div class="column_link">
                                    <a href="#">Site Map</a>
                                    <a href="#">Search Terms</a>
                                    <a href="#">Advanced Search</a>
                                    <a href="#">Mobile</a>
                                    <a href="#">Contact Us</a>
                                    <a href="#">Mobile</a>
                                    <a href="#">Addresses</a>
                                </div>
                            </div>
                            <div class="news_letter">
                                <div class="column_head">
                                    NewsLetter
                                </div>
                                <div class="news_content">
                                    <div class="news_content_text">
                                        Join thousands of other people subscribe to our news
                                    </div>
                                    <input type="text" placeholder="Insert e-mail">
                                    <button>SUBMIT</button>
                                    <div class="cards_wrap">
                                        <img src=" {% static 'server/img/payment_methods/american-express.jpg' %}" alt="">
                                        <img src=" {% static 'server/img/payment_methods/master-card.jpg' %}" alt="">
                                        <img src=" {% static 'server/img/payment_methods/maestro.jpg' %}" alt="">
                                        <img src=" {% static 'server/img/payment_methods/paypal.jpg' %}" alt="">
                                        <img src=" {% static 'server/img/payment_methods/discover.jpg' %}" alt="">
                                        <img src=" {% static 'server/img/payment_methods/visa.jpg' %}" alt="">
                                    </div>
                                </div>
                            </div>
                            <div class="about">
                                <div class="column_head">
                                    About Us
                                </div>
                                <div class="about_text_wrap">
                                    <div class="about_text">
                                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni dolorum distinctio
                                        laudantium ipsum obcaecati sapiente nemo sequi perferendis corporis neque modi ullam,
                                        quisquam consequuntur tempora nostrum at ipsam nobis officia?
                                    </div>
                                    <div class="about_phone">
                                        <span>Phone:</span> +354 (354) 123-456
                                    </div>
                                    <div class="about_email">
                                        <span>e-mail:</span> contact@shop.com
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endblock %}

            {% block footer_copyrights %}
                <div class="footer_copyrights">
                    <div class="main_wrap">
                        <div class="footer_copyrights_text">
                            © 2018 Сундук с сокровищами. Все права защищены - Designed by St.Shorh
                        </div>
                        <div class="footer_copyrights_social">
                            <a href="#">
                                <i class="fab fa-facebook-f"></i>
                            </a>
                            <a href="#">
                                <i class="fab fa-twitter"></i>
                            </a>
                            <a href="#">
                                <i class="fab fa-pinterest-p"></i>
                            </a>
                            <a href="#">
                                <i class="fab fa-google-plus-g"></i>
                            </a>
                            <a href="#">
                                <i class="fab fa-tumblr"></i>
                            </a>
                            <a href="#">
                                <i class="fab fa-instagram"></i>
                            </a>
                            <a href="#">
                                <i class="fas fa-rss"></i>
                            </a>
                        </div>
                    </div>
                </div>
            {% endblock %}

            {% block page_scripts %}
            {% endblock %}
        </body>
    {% endblock %}
</html>